namespace OCR_PROYEKTO
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            Utilities.BunifuPages.BunifuAnimatorNS.Animation animation1 = new Utilities.BunifuPages.BunifuAnimatorNS.Animation();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.bunifuFormDock1 = new Bunifu.UI.WinForms.BunifuFormDock();
            this.Signup_tab = new Bunifu.UI.WinForms.BunifuPages();
            this.Signin_tab = new System.Windows.Forms.TabPage();
            this.bunifuSeparator1 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuButton2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtpass = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtemail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuLabel3 = new Bunifu.UI.WinForms.BunifuLabel();
            this.tabPage2 = new System.Windows.Forms.TabPage();
            this.create_email = new Bunifu.UI.WinForms.BunifuTextBox();
            this.create_pass = new Bunifu.UI.WinForms.BunifuTextBox();
            this.create_name = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bunifuSeparator2 = new Bunifu.UI.WinForms.BunifuSeparator();
            this.bunifuButton3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel4 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            this.register_toggle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.Sign_toggle = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bunifuLabel2 = new Bunifu.UI.WinForms.BunifuLabel();
            this.bunifuLabel1 = new Bunifu.UI.WinForms.BunifuLabel();
            this.Signup_tab.SuspendLayout();
            this.Signin_tab.SuspendLayout();
            this.tabPage2.SuspendLayout();
            this.bunifuGradientPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // bunifuFormDock1
            // 
            this.bunifuFormDock1.AllowFormDragging = true;
            this.bunifuFormDock1.AllowFormDropShadow = true;
            this.bunifuFormDock1.AllowFormResizing = false;
            this.bunifuFormDock1.AllowHidingBottomRegion = true;
            this.bunifuFormDock1.AllowOpacityChangesWhileDragging = false;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.BottomBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.BottomBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.LeftBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.LeftBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.RightBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.RightBorder.ShowBorder = true;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderColor = System.Drawing.Color.Silver;
            this.bunifuFormDock1.BorderOptions.TopBorder.BorderThickness = 1;
            this.bunifuFormDock1.BorderOptions.TopBorder.ShowBorder = true;
            this.bunifuFormDock1.ContainerControl = this;
            this.bunifuFormDock1.DockingIndicatorsColor = System.Drawing.Color.FromArgb(((int)(((byte)(202)))), ((int)(((byte)(215)))), ((int)(((byte)(233)))));
            this.bunifuFormDock1.DockingIndicatorsOpacity = 0.5D;
            this.bunifuFormDock1.DockingOptions.DockAll = true;
            this.bunifuFormDock1.DockingOptions.DockBottomLeft = true;
            this.bunifuFormDock1.DockingOptions.DockBottomRight = true;
            this.bunifuFormDock1.DockingOptions.DockFullScreen = true;
            this.bunifuFormDock1.DockingOptions.DockLeft = true;
            this.bunifuFormDock1.DockingOptions.DockRight = true;
            this.bunifuFormDock1.DockingOptions.DockTopLeft = true;
            this.bunifuFormDock1.DockingOptions.DockTopRight = true;
            this.bunifuFormDock1.FormDraggingOpacity = 0.9D;
            this.bunifuFormDock1.ParentForm = this;
            this.bunifuFormDock1.ShowCursorChanges = true;
            this.bunifuFormDock1.ShowDockingIndicators = false;
            this.bunifuFormDock1.TitleBarOptions.AllowFormDragging = true;
            this.bunifuFormDock1.TitleBarOptions.BunifuFormDock = this.bunifuFormDock1;
            this.bunifuFormDock1.TitleBarOptions.DoubleClickToExpandWindow = true;
            this.bunifuFormDock1.TitleBarOptions.TitleBarControl = null;
            this.bunifuFormDock1.TitleBarOptions.UseBackColorOnDockingIndicators = false;
            // 
            // Signup_tab
            // 
            this.Signup_tab.Alignment = System.Windows.Forms.TabAlignment.Bottom;
            this.Signup_tab.AllowTransitions = true;
            this.Signup_tab.Controls.Add(this.Signin_tab);
            this.Signup_tab.Controls.Add(this.tabPage2);
            this.Signup_tab.Dock = System.Windows.Forms.DockStyle.Fill;
            this.Signup_tab.Location = new System.Drawing.Point(479, 0);
            this.Signup_tab.Multiline = true;
            this.Signup_tab.Name = "Signup_tab";
            this.Signup_tab.Page = this.Signin_tab;
            this.Signup_tab.PageIndex = 0;
            this.Signup_tab.PageName = "Signin_tab";
            this.Signup_tab.PageTitle = "sign_in";
            this.Signup_tab.SelectedIndex = 0;
            this.Signup_tab.Size = new System.Drawing.Size(527, 583);
            this.Signup_tab.TabIndex = 1;
            animation1.AnimateOnlyDifferences = false;
            animation1.BlindCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.BlindCoeff")));
            animation1.LeafCoeff = 0F;
            animation1.MaxTime = 1F;
            animation1.MinTime = 0F;
            animation1.MosaicCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicCoeff")));
            animation1.MosaicShift = ((System.Drawing.PointF)(resources.GetObject("animation1.MosaicShift")));
            animation1.MosaicSize = 0;
            animation1.Padding = new System.Windows.Forms.Padding(0);
            animation1.RotateCoeff = 0F;
            animation1.RotateLimit = 0F;
            animation1.ScaleCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.ScaleCoeff")));
            animation1.SlideCoeff = ((System.Drawing.PointF)(resources.GetObject("animation1.SlideCoeff")));
            animation1.TimeCoeff = 0F;
            animation1.TransparencyCoeff = 0F;
            this.Signup_tab.Transition = animation1;
            this.Signup_tab.TransitionType = Utilities.BunifuPages.BunifuAnimatorNS.AnimationType.Custom;
            // 
            // Signin_tab
            // 
            this.Signin_tab.Controls.Add(this.bunifuSeparator1);
            this.Signin_tab.Controls.Add(this.bunifuButton2);
            this.Signin_tab.Controls.Add(this.txtpass);
            this.Signin_tab.Controls.Add(this.txtemail);
            this.Signin_tab.Controls.Add(this.bunifuLabel3);
            this.Signin_tab.Location = new System.Drawing.Point(4, 4);
            this.Signin_tab.Name = "Signin_tab";
            this.Signin_tab.Padding = new System.Windows.Forms.Padding(3);
            this.Signin_tab.Size = new System.Drawing.Size(519, 557);
            this.Signin_tab.TabIndex = 0;
            this.Signin_tab.Text = "sign_in";
            this.Signin_tab.UseVisualStyleBackColor = true;
            // 
            // bunifuSeparator1
            // 
            this.bunifuSeparator1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator1.BackgroundImage")));
            this.bunifuSeparator1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator1.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator1.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator1.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator1.LineThickness = 3;
            this.bunifuSeparator1.Location = new System.Drawing.Point(61, 137);
            this.bunifuSeparator1.Name = "bunifuSeparator1";
            this.bunifuSeparator1.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator1.Size = new System.Drawing.Size(151, 14);
            this.bunifuSeparator1.TabIndex = 6;
            // 
            // bunifuButton2
            // 
            this.bunifuButton2.AllowToggling = false;
            this.bunifuButton2.AnimationSpeed = 200;
            this.bunifuButton2.AutoGenerateColors = false;
            this.bunifuButton2.AutoSizeLeftIcon = true;
            this.bunifuButton2.AutoSizeRightIcon = true;
            this.bunifuButton2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton2.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuButton2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton2.BackgroundImage")));
            this.bunifuButton2.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.ButtonText = "SIGN IN";
            this.bunifuButton2.ButtonTextMarginLeft = 0;
            this.bunifuButton2.ColorContrastOnClick = 45;
            this.bunifuButton2.ColorContrastOnHover = 45;
            this.bunifuButton2.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.bunifuButton2.CustomizableEdges = borderEdges1;
            this.bunifuButton2.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton2.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton2.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton2.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton2.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton2.IconMarginLeft = 11;
            this.bunifuButton2.IconPadding = 10;
            this.bunifuButton2.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton2.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton2.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton2.IconSize = 25;
            this.bunifuButton2.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.IdleBorderRadius = 34;
            this.bunifuButton2.IdleBorderThickness = 1;
            this.bunifuButton2.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuButton2.IdleIconLeftImage = null;
            this.bunifuButton2.IdleIconRightImage = null;
            this.bunifuButton2.IndicateFocus = false;
            this.bunifuButton2.Location = new System.Drawing.Point(216, 351);
            this.bunifuButton2.Name = "bunifuButton2";
            this.bunifuButton2.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton2.OnDisabledState.BorderRadius = 34;
            this.bunifuButton2.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnDisabledState.BorderThickness = 1;
            this.bunifuButton2.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton2.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton2.OnDisabledState.IconLeftImage = null;
            this.bunifuButton2.OnDisabledState.IconRightImage = null;
            this.bunifuButton2.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.BorderRadius = 34;
            this.bunifuButton2.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.onHoverState.BorderThickness = 1;
            this.bunifuButton2.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton2.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.onHoverState.IconLeftImage = null;
            this.bunifuButton2.onHoverState.IconRightImage = null;
            this.bunifuButton2.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.bunifuButton2.OnIdleState.BorderRadius = 34;
            this.bunifuButton2.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnIdleState.BorderThickness = 1;
            this.bunifuButton2.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuButton2.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnIdleState.IconLeftImage = null;
            this.bunifuButton2.OnIdleState.IconRightImage = null;
            this.bunifuButton2.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton2.OnPressedState.BorderRadius = 34;
            this.bunifuButton2.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton2.OnPressedState.BorderThickness = 1;
            this.bunifuButton2.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton2.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton2.OnPressedState.IconLeftImage = null;
            this.bunifuButton2.OnPressedState.IconRightImage = null;
            this.bunifuButton2.Size = new System.Drawing.Size(216, 54);
            this.bunifuButton2.TabIndex = 5;
            this.bunifuButton2.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton2.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton2.TextMarginLeft = 0;
            this.bunifuButton2.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton2.UseDefaultRadiusAndThickness = true;
            this.bunifuButton2.Click += new System.EventHandler(this.bunifuButton2_Click);
            // 
            // txtpass
            // 
            this.txtpass.AcceptsReturn = false;
            this.txtpass.AcceptsTab = false;
            this.txtpass.AnimationSpeed = 200;
            this.txtpass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtpass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtpass.BackColor = System.Drawing.Color.Transparent;
            this.txtpass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtpass.BackgroundImage")));
            this.txtpass.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtpass.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtpass.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtpass.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtpass.BorderRadius = 1;
            this.txtpass.BorderThickness = 1;
            this.txtpass.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtpass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpass.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtpass.DefaultText = "";
            this.txtpass.FillColor = System.Drawing.Color.White;
            this.txtpass.HideSelection = true;
            this.txtpass.IconLeft = global::OCR_PROYEKTO.Properties.Resources.password_30px;
            this.txtpass.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpass.IconPadding = 10;
            this.txtpass.IconRight = null;
            this.txtpass.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtpass.Lines = new string[0];
            this.txtpass.Location = new System.Drawing.Point(61, 267);
            this.txtpass.MaxLength = 32767;
            this.txtpass.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtpass.Modified = false;
            this.txtpass.Multiline = false;
            this.txtpass.Name = "txtpass";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpass.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtpass.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpass.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtpass.OnIdleState = stateProperties4;
            this.txtpass.Padding = new System.Windows.Forms.Padding(3);
            this.txtpass.PasswordChar = '•';
            this.txtpass.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtpass.PlaceholderText = "Enter password";
            this.txtpass.ReadOnly = false;
            this.txtpass.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtpass.SelectedText = "";
            this.txtpass.SelectionLength = 0;
            this.txtpass.SelectionStart = 0;
            this.txtpass.ShortcutsEnabled = true;
            this.txtpass.Size = new System.Drawing.Size(371, 37);
            this.txtpass.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtpass.TabIndex = 4;
            this.txtpass.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtpass.TextMarginBottom = 0;
            this.txtpass.TextMarginLeft = 15;
            this.txtpass.TextMarginTop = 0;
            this.txtpass.TextPlaceholder = "Enter password";
            this.txtpass.UseSystemPasswordChar = false;
            this.txtpass.WordWrap = true;
            this.txtpass.TextChanged += new System.EventHandler(this.bunifuTextBox2_TextChanged);
            // 
            // txtemail
            // 
            this.txtemail.AcceptsReturn = false;
            this.txtemail.AcceptsTab = false;
            this.txtemail.AnimationSpeed = 200;
            this.txtemail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtemail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtemail.BackColor = System.Drawing.Color.Transparent;
            this.txtemail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtemail.BackgroundImage")));
            this.txtemail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtemail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtemail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtemail.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtemail.BorderRadius = 1;
            this.txtemail.BorderThickness = 1;
            this.txtemail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtemail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtemail.DefaultText = "";
            this.txtemail.FillColor = System.Drawing.Color.White;
            this.txtemail.HideSelection = true;
            this.txtemail.IconLeft = global::OCR_PROYEKTO.Properties.Resources.user_groups_64px;
            this.txtemail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.IconPadding = 10;
            this.txtemail.IconRight = null;
            this.txtemail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtemail.Lines = new string[0];
            this.txtemail.Location = new System.Drawing.Point(61, 203);
            this.txtemail.MaxLength = 32767;
            this.txtemail.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtemail.Modified = false;
            this.txtemail.Multiline = false;
            this.txtemail.Name = "txtemail";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtemail.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtemail.OnIdleState = stateProperties8;
            this.txtemail.Padding = new System.Windows.Forms.Padding(3);
            this.txtemail.PasswordChar = '\0';
            this.txtemail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtemail.PlaceholderText = "Enter name";
            this.txtemail.ReadOnly = false;
            this.txtemail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtemail.SelectedText = "";
            this.txtemail.SelectionLength = 0;
            this.txtemail.SelectionStart = 0;
            this.txtemail.ShortcutsEnabled = true;
            this.txtemail.Size = new System.Drawing.Size(371, 37);
            this.txtemail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtemail.TabIndex = 3;
            this.txtemail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtemail.TextMarginBottom = 0;
            this.txtemail.TextMarginLeft = 15;
            this.txtemail.TextMarginTop = 0;
            this.txtemail.TextPlaceholder = "Enter name";
            this.txtemail.UseSystemPasswordChar = false;
            this.txtemail.WordWrap = true;
            // 
            // bunifuLabel3
            // 
            this.bunifuLabel3.AllowParentOverrides = false;
            this.bunifuLabel3.AutoEllipsis = false;
            this.bunifuLabel3.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel3.Font = new System.Drawing.Font("Segoe UI Semibold", 36F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel3.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuLabel3.Location = new System.Drawing.Point(61, 66);
            this.bunifuLabel3.Name = "bunifuLabel3";
            this.bunifuLabel3.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel3.Size = new System.Drawing.Size(151, 65);
            this.bunifuLabel3.TabIndex = 2;
            this.bunifuLabel3.Text = "Sign In";
            this.bunifuLabel3.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel3.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // tabPage2
            // 
            this.tabPage2.Controls.Add(this.create_email);
            this.tabPage2.Controls.Add(this.create_pass);
            this.tabPage2.Controls.Add(this.create_name);
            this.tabPage2.Controls.Add(this.bunifuSeparator2);
            this.tabPage2.Controls.Add(this.bunifuButton3);
            this.tabPage2.Controls.Add(this.bunifuLabel4);
            this.tabPage2.Location = new System.Drawing.Point(4, 4);
            this.tabPage2.Name = "tabPage2";
            this.tabPage2.Padding = new System.Windows.Forms.Padding(3);
            this.tabPage2.Size = new System.Drawing.Size(519, 557);
            this.tabPage2.TabIndex = 1;
            this.tabPage2.Text = "sign_up";
            this.tabPage2.UseVisualStyleBackColor = true;
            // 
            // create_email
            // 
            this.create_email.AcceptsReturn = false;
            this.create_email.AcceptsTab = false;
            this.create_email.AnimationSpeed = 200;
            this.create_email.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.create_email.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.create_email.BackColor = System.Drawing.Color.Transparent;
            this.create_email.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("create_email.BackgroundImage")));
            this.create_email.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.create_email.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.create_email.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.create_email.BorderColorIdle = System.Drawing.Color.Silver;
            this.create_email.BorderRadius = 1;
            this.create_email.BorderThickness = 1;
            this.create_email.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.create_email.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.create_email.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.create_email.DefaultText = "";
            this.create_email.FillColor = System.Drawing.Color.White;
            this.create_email.HideSelection = true;
            this.create_email.IconLeft = global::OCR_PROYEKTO.Properties.Resources.email_64px;
            this.create_email.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.create_email.IconPadding = 10;
            this.create_email.IconRight = null;
            this.create_email.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.create_email.Lines = new string[0];
            this.create_email.Location = new System.Drawing.Point(65, 240);
            this.create_email.MaxLength = 32767;
            this.create_email.MinimumSize = new System.Drawing.Size(1, 1);
            this.create_email.Modified = false;
            this.create_email.Multiline = false;
            this.create_email.Name = "create_email";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.create_email.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.create_email.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.create_email.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.create_email.OnIdleState = stateProperties12;
            this.create_email.Padding = new System.Windows.Forms.Padding(3);
            this.create_email.PasswordChar = '\0';
            this.create_email.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.create_email.PlaceholderText = "Enter email";
            this.create_email.ReadOnly = false;
            this.create_email.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.create_email.SelectedText = "";
            this.create_email.SelectionLength = 0;
            this.create_email.SelectionStart = 0;
            this.create_email.ShortcutsEnabled = true;
            this.create_email.Size = new System.Drawing.Size(371, 37);
            this.create_email.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.create_email.TabIndex = 14;
            this.create_email.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.create_email.TextMarginBottom = 0;
            this.create_email.TextMarginLeft = 15;
            this.create_email.TextMarginTop = 0;
            this.create_email.TextPlaceholder = "Enter email";
            this.create_email.UseSystemPasswordChar = false;
            this.create_email.WordWrap = true;
            // 
            // create_pass
            // 
            this.create_pass.AcceptsReturn = false;
            this.create_pass.AcceptsTab = false;
            this.create_pass.AnimationSpeed = 200;
            this.create_pass.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.create_pass.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.create_pass.BackColor = System.Drawing.Color.Transparent;
            this.create_pass.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("create_pass.BackgroundImage")));
            this.create_pass.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.create_pass.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.create_pass.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.create_pass.BorderColorIdle = System.Drawing.Color.Silver;
            this.create_pass.BorderRadius = 1;
            this.create_pass.BorderThickness = 1;
            this.create_pass.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.create_pass.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.create_pass.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.create_pass.DefaultText = "";
            this.create_pass.FillColor = System.Drawing.Color.White;
            this.create_pass.HideSelection = true;
            this.create_pass.IconLeft = global::OCR_PROYEKTO.Properties.Resources.password_30px;
            this.create_pass.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.create_pass.IconPadding = 10;
            this.create_pass.IconRight = null;
            this.create_pass.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.create_pass.Lines = new string[0];
            this.create_pass.Location = new System.Drawing.Point(65, 295);
            this.create_pass.MaxLength = 32767;
            this.create_pass.MinimumSize = new System.Drawing.Size(1, 1);
            this.create_pass.Modified = false;
            this.create_pass.Multiline = false;
            this.create_pass.Name = "create_pass";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.create_pass.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.create_pass.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.create_pass.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.create_pass.OnIdleState = stateProperties16;
            this.create_pass.Padding = new System.Windows.Forms.Padding(3);
            this.create_pass.PasswordChar = '•';
            this.create_pass.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.create_pass.PlaceholderText = "Enter password";
            this.create_pass.ReadOnly = false;
            this.create_pass.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.create_pass.SelectedText = "";
            this.create_pass.SelectionLength = 0;
            this.create_pass.SelectionStart = 0;
            this.create_pass.ShortcutsEnabled = true;
            this.create_pass.Size = new System.Drawing.Size(371, 37);
            this.create_pass.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.create_pass.TabIndex = 13;
            this.create_pass.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.create_pass.TextMarginBottom = 0;
            this.create_pass.TextMarginLeft = 15;
            this.create_pass.TextMarginTop = 0;
            this.create_pass.TextPlaceholder = "Enter password";
            this.create_pass.UseSystemPasswordChar = false;
            this.create_pass.WordWrap = true;
            // 
            // create_name
            // 
            this.create_name.AcceptsReturn = false;
            this.create_name.AcceptsTab = false;
            this.create_name.AnimationSpeed = 200;
            this.create_name.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.create_name.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.create_name.BackColor = System.Drawing.Color.Transparent;
            this.create_name.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("create_name.BackgroundImage")));
            this.create_name.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.create_name.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.create_name.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.create_name.BorderColorIdle = System.Drawing.Color.Silver;
            this.create_name.BorderRadius = 1;
            this.create_name.BorderThickness = 1;
            this.create_name.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.create_name.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.create_name.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.create_name.DefaultText = "";
            this.create_name.FillColor = System.Drawing.Color.White;
            this.create_name.HideSelection = true;
            this.create_name.IconLeft = global::OCR_PROYEKTO.Properties.Resources.user_groups_64px;
            this.create_name.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.create_name.IconPadding = 10;
            this.create_name.IconRight = null;
            this.create_name.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.create_name.Lines = new string[0];
            this.create_name.Location = new System.Drawing.Point(65, 186);
            this.create_name.MaxLength = 32767;
            this.create_name.MinimumSize = new System.Drawing.Size(1, 1);
            this.create_name.Modified = false;
            this.create_name.Multiline = false;
            this.create_name.Name = "create_name";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.create_name.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.create_name.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.create_name.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.create_name.OnIdleState = stateProperties20;
            this.create_name.Padding = new System.Windows.Forms.Padding(3);
            this.create_name.PasswordChar = '\0';
            this.create_name.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.create_name.PlaceholderText = "Enter name";
            this.create_name.ReadOnly = false;
            this.create_name.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.create_name.SelectedText = "";
            this.create_name.SelectionLength = 0;
            this.create_name.SelectionStart = 0;
            this.create_name.ShortcutsEnabled = true;
            this.create_name.Size = new System.Drawing.Size(371, 37);
            this.create_name.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.create_name.TabIndex = 12;
            this.create_name.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.create_name.TextMarginBottom = 0;
            this.create_name.TextMarginLeft = 15;
            this.create_name.TextMarginTop = 0;
            this.create_name.TextPlaceholder = "Enter name";
            this.create_name.UseSystemPasswordChar = false;
            this.create_name.WordWrap = true;
            // 
            // bunifuSeparator2
            // 
            this.bunifuSeparator2.BackColor = System.Drawing.Color.Transparent;
            this.bunifuSeparator2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuSeparator2.BackgroundImage")));
            this.bunifuSeparator2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuSeparator2.DashCap = Bunifu.UI.WinForms.BunifuSeparator.CapStyles.Flat;
            this.bunifuSeparator2.LineColor = System.Drawing.Color.Silver;
            this.bunifuSeparator2.LineStyle = Bunifu.UI.WinForms.BunifuSeparator.LineStyles.Solid;
            this.bunifuSeparator2.LineThickness = 3;
            this.bunifuSeparator2.Location = new System.Drawing.Point(83, 137);
            this.bunifuSeparator2.Name = "bunifuSeparator2";
            this.bunifuSeparator2.Orientation = Bunifu.UI.WinForms.BunifuSeparator.LineOrientation.Horizontal;
            this.bunifuSeparator2.Size = new System.Drawing.Size(335, 14);
            this.bunifuSeparator2.TabIndex = 11;
            // 
            // bunifuButton3
            // 
            this.bunifuButton3.AllowToggling = false;
            this.bunifuButton3.AnimationSpeed = 200;
            this.bunifuButton3.AutoGenerateColors = false;
            this.bunifuButton3.AutoSizeLeftIcon = true;
            this.bunifuButton3.AutoSizeRightIcon = true;
            this.bunifuButton3.BackColor = System.Drawing.Color.Transparent;
            this.bunifuButton3.BackColor1 = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuButton3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuButton3.BackgroundImage")));
            this.bunifuButton3.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.ButtonText = "Create";
            this.bunifuButton3.ButtonTextMarginLeft = 0;
            this.bunifuButton3.ColorContrastOnClick = 45;
            this.bunifuButton3.ColorContrastOnHover = 45;
            this.bunifuButton3.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.bunifuButton3.CustomizableEdges = borderEdges2;
            this.bunifuButton3.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bunifuButton3.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.bunifuButton3.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuButton3.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.bunifuButton3.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.bunifuButton3.IconMarginLeft = 11;
            this.bunifuButton3.IconPadding = 10;
            this.bunifuButton3.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.bunifuButton3.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.bunifuButton3.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.bunifuButton3.IconSize = 25;
            this.bunifuButton3.IdleBorderColor = System.Drawing.Color.Empty;
            this.bunifuButton3.IdleBorderRadius = 34;
            this.bunifuButton3.IdleBorderThickness = 1;
            this.bunifuButton3.IdleFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuButton3.IdleIconLeftImage = null;
            this.bunifuButton3.IdleIconRightImage = null;
            this.bunifuButton3.IndicateFocus = false;
            this.bunifuButton3.Location = new System.Drawing.Point(220, 368);
            this.bunifuButton3.Name = "bunifuButton3";
            this.bunifuButton3.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.bunifuButton3.OnDisabledState.BorderRadius = 34;
            this.bunifuButton3.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnDisabledState.BorderThickness = 1;
            this.bunifuButton3.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bunifuButton3.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.bunifuButton3.OnDisabledState.IconLeftImage = null;
            this.bunifuButton3.OnDisabledState.IconRightImage = null;
            this.bunifuButton3.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.BorderRadius = 34;
            this.bunifuButton3.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.onHoverState.BorderThickness = 1;
            this.bunifuButton3.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bunifuButton3.onHoverState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.onHoverState.IconLeftImage = null;
            this.bunifuButton3.onHoverState.IconRightImage = null;
            this.bunifuButton3.OnIdleState.BorderColor = System.Drawing.Color.Empty;
            this.bunifuButton3.OnIdleState.BorderRadius = 34;
            this.bunifuButton3.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnIdleState.BorderThickness = 1;
            this.bunifuButton3.OnIdleState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuButton3.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnIdleState.IconLeftImage = null;
            this.bunifuButton3.OnIdleState.IconRightImage = null;
            this.bunifuButton3.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.bunifuButton3.OnPressedState.BorderRadius = 34;
            this.bunifuButton3.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.bunifuButton3.OnPressedState.BorderThickness = 1;
            this.bunifuButton3.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuButton3.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.bunifuButton3.OnPressedState.IconLeftImage = null;
            this.bunifuButton3.OnPressedState.IconRightImage = null;
            this.bunifuButton3.Size = new System.Drawing.Size(216, 54);
            this.bunifuButton3.TabIndex = 10;
            this.bunifuButton3.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.bunifuButton3.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.bunifuButton3.TextMarginLeft = 0;
            this.bunifuButton3.TextPadding = new System.Windows.Forms.Padding(0);
            this.bunifuButton3.UseDefaultRadiusAndThickness = true;
            this.bunifuButton3.Click += new System.EventHandler(this.bunifuButton3_Click);
            // 
            // bunifuLabel4
            // 
            this.bunifuLabel4.AllowParentOverrides = false;
            this.bunifuLabel4.AutoEllipsis = false;
            this.bunifuLabel4.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel4.Font = new System.Drawing.Font("Segoe UI Semibold", 36F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel4.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuLabel4.Location = new System.Drawing.Point(83, 66);
            this.bunifuLabel4.Name = "bunifuLabel4";
            this.bunifuLabel4.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel4.Size = new System.Drawing.Size(335, 65);
            this.bunifuLabel4.TabIndex = 7;
            this.bunifuLabel4.Text = "Create Account";
            this.bunifuLabel4.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel4.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // bunifuGradientPanel1
            // 
            this.bunifuGradientPanel1.BackColor = System.Drawing.SystemColors.Control;
            this.bunifuGradientPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuGradientPanel1.BackgroundImage")));
            this.bunifuGradientPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuGradientPanel1.BorderRadius = 1;
            this.bunifuGradientPanel1.Controls.Add(this.register_toggle);
            this.bunifuGradientPanel1.Controls.Add(this.Sign_toggle);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel2);
            this.bunifuGradientPanel1.Controls.Add(this.bunifuLabel1);
            this.bunifuGradientPanel1.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuGradientPanel1.GradientBottomLeft = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuGradientPanel1.GradientBottomRight = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuGradientPanel1.GradientTopLeft = System.Drawing.Color.FromArgb(((int)(((byte)(128)))), ((int)(((byte)(128)))), ((int)(((byte)(255)))));
            this.bunifuGradientPanel1.GradientTopRight = System.Drawing.Color.FromArgb(((int)(((byte)(54)))), ((int)(((byte)(173)))), ((int)(((byte)(164)))));
            this.bunifuGradientPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            this.bunifuGradientPanel1.Quality = 10;
            this.bunifuGradientPanel1.Size = new System.Drawing.Size(479, 583);
            this.bunifuGradientPanel1.TabIndex = 0;
            // 
            // register_toggle
            // 
            this.register_toggle.AllowToggling = false;
            this.register_toggle.AnimationSpeed = 200;
            this.register_toggle.AutoGenerateColors = false;
            this.register_toggle.AutoSizeLeftIcon = true;
            this.register_toggle.AutoSizeRightIcon = true;
            this.register_toggle.BackColor = System.Drawing.Color.Transparent;
            this.register_toggle.BackColor1 = System.Drawing.Color.Transparent;
            this.register_toggle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("register_toggle.BackgroundImage")));
            this.register_toggle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.register_toggle.ButtonText = "REGISTER";
            this.register_toggle.ButtonTextMarginLeft = 0;
            this.register_toggle.ColorContrastOnClick = 45;
            this.register_toggle.ColorContrastOnHover = 45;
            this.register_toggle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.register_toggle.CustomizableEdges = borderEdges3;
            this.register_toggle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.register_toggle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.register_toggle.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.register_toggle.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.register_toggle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.register_toggle.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.register_toggle.ForeColor = System.Drawing.Color.White;
            this.register_toggle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.register_toggle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.register_toggle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.register_toggle.IconMarginLeft = 11;
            this.register_toggle.IconPadding = 10;
            this.register_toggle.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.register_toggle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.register_toggle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.register_toggle.IconSize = 25;
            this.register_toggle.IdleBorderColor = System.Drawing.Color.WhiteSmoke;
            this.register_toggle.IdleBorderRadius = 34;
            this.register_toggle.IdleBorderThickness = 1;
            this.register_toggle.IdleFillColor = System.Drawing.Color.Transparent;
            this.register_toggle.IdleIconLeftImage = null;
            this.register_toggle.IdleIconRightImage = null;
            this.register_toggle.IndicateFocus = false;
            this.register_toggle.Location = new System.Drawing.Point(116, 436);
            this.register_toggle.Name = "register_toggle";
            this.register_toggle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.register_toggle.OnDisabledState.BorderRadius = 34;
            this.register_toggle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.register_toggle.OnDisabledState.BorderThickness = 1;
            this.register_toggle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.register_toggle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.register_toggle.OnDisabledState.IconLeftImage = null;
            this.register_toggle.OnDisabledState.IconRightImage = null;
            this.register_toggle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.register_toggle.onHoverState.BorderRadius = 34;
            this.register_toggle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.register_toggle.onHoverState.BorderThickness = 1;
            this.register_toggle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.register_toggle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.register_toggle.onHoverState.IconLeftImage = null;
            this.register_toggle.onHoverState.IconRightImage = null;
            this.register_toggle.OnIdleState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.register_toggle.OnIdleState.BorderRadius = 34;
            this.register_toggle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.register_toggle.OnIdleState.BorderThickness = 1;
            this.register_toggle.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.register_toggle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.register_toggle.OnIdleState.IconLeftImage = null;
            this.register_toggle.OnIdleState.IconRightImage = null;
            this.register_toggle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.register_toggle.OnPressedState.BorderRadius = 34;
            this.register_toggle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.register_toggle.OnPressedState.BorderThickness = 1;
            this.register_toggle.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.register_toggle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.register_toggle.OnPressedState.IconLeftImage = null;
            this.register_toggle.OnPressedState.IconRightImage = null;
            this.register_toggle.Size = new System.Drawing.Size(216, 54);
            this.register_toggle.TabIndex = 4;
            this.register_toggle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.register_toggle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.register_toggle.TextMarginLeft = 0;
            this.register_toggle.TextPadding = new System.Windows.Forms.Padding(0);
            this.register_toggle.UseDefaultRadiusAndThickness = true;
            this.register_toggle.Click += new System.EventHandler(this.register_toggle_Click);
            // 
            // Sign_toggle
            // 
            this.Sign_toggle.AllowToggling = false;
            this.Sign_toggle.AnimationSpeed = 200;
            this.Sign_toggle.AutoGenerateColors = false;
            this.Sign_toggle.AutoSizeLeftIcon = true;
            this.Sign_toggle.AutoSizeRightIcon = true;
            this.Sign_toggle.BackColor = System.Drawing.Color.Transparent;
            this.Sign_toggle.BackColor1 = System.Drawing.Color.Transparent;
            this.Sign_toggle.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("Sign_toggle.BackgroundImage")));
            this.Sign_toggle.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Sign_toggle.ButtonText = "SIGN IN";
            this.Sign_toggle.ButtonTextMarginLeft = 0;
            this.Sign_toggle.ColorContrastOnClick = 45;
            this.Sign_toggle.ColorContrastOnHover = 45;
            this.Sign_toggle.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.Sign_toggle.CustomizableEdges = borderEdges4;
            this.Sign_toggle.DialogResult = System.Windows.Forms.DialogResult.None;
            this.Sign_toggle.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Sign_toggle.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Sign_toggle.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Sign_toggle.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.Sign_toggle.Font = new System.Drawing.Font("Segoe UI", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.Sign_toggle.ForeColor = System.Drawing.Color.White;
            this.Sign_toggle.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.Sign_toggle.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.Sign_toggle.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.Sign_toggle.IconMarginLeft = 11;
            this.Sign_toggle.IconPadding = 10;
            this.Sign_toggle.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.Sign_toggle.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.Sign_toggle.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.Sign_toggle.IconSize = 25;
            this.Sign_toggle.IdleBorderColor = System.Drawing.Color.WhiteSmoke;
            this.Sign_toggle.IdleBorderRadius = 34;
            this.Sign_toggle.IdleBorderThickness = 1;
            this.Sign_toggle.IdleFillColor = System.Drawing.Color.Transparent;
            this.Sign_toggle.IdleIconLeftImage = null;
            this.Sign_toggle.IdleIconRightImage = null;
            this.Sign_toggle.IndicateFocus = false;
            this.Sign_toggle.Location = new System.Drawing.Point(116, 367);
            this.Sign_toggle.Name = "Sign_toggle";
            this.Sign_toggle.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.Sign_toggle.OnDisabledState.BorderRadius = 34;
            this.Sign_toggle.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Sign_toggle.OnDisabledState.BorderThickness = 1;
            this.Sign_toggle.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.Sign_toggle.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.Sign_toggle.OnDisabledState.IconLeftImage = null;
            this.Sign_toggle.OnDisabledState.IconRightImage = null;
            this.Sign_toggle.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Sign_toggle.onHoverState.BorderRadius = 34;
            this.Sign_toggle.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Sign_toggle.onHoverState.BorderThickness = 1;
            this.Sign_toggle.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.Sign_toggle.onHoverState.ForeColor = System.Drawing.Color.White;
            this.Sign_toggle.onHoverState.IconLeftImage = null;
            this.Sign_toggle.onHoverState.IconRightImage = null;
            this.Sign_toggle.OnIdleState.BorderColor = System.Drawing.Color.WhiteSmoke;
            this.Sign_toggle.OnIdleState.BorderRadius = 34;
            this.Sign_toggle.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Sign_toggle.OnIdleState.BorderThickness = 1;
            this.Sign_toggle.OnIdleState.FillColor = System.Drawing.Color.Transparent;
            this.Sign_toggle.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.Sign_toggle.OnIdleState.IconLeftImage = null;
            this.Sign_toggle.OnIdleState.IconRightImage = null;
            this.Sign_toggle.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.Sign_toggle.OnPressedState.BorderRadius = 34;
            this.Sign_toggle.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.Sign_toggle.OnPressedState.BorderThickness = 1;
            this.Sign_toggle.OnPressedState.FillColor = System.Drawing.Color.WhiteSmoke;
            this.Sign_toggle.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.Sign_toggle.OnPressedState.IconLeftImage = null;
            this.Sign_toggle.OnPressedState.IconRightImage = null;
            this.Sign_toggle.Size = new System.Drawing.Size(216, 54);
            this.Sign_toggle.TabIndex = 3;
            this.Sign_toggle.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.Sign_toggle.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.Sign_toggle.TextMarginLeft = 0;
            this.Sign_toggle.TextPadding = new System.Windows.Forms.Padding(0);
            this.Sign_toggle.UseDefaultRadiusAndThickness = true;
            this.Sign_toggle.Click += new System.EventHandler(this.Sign_toggle_Click);
            // 
            // bunifuLabel2
            // 
            this.bunifuLabel2.AllowParentOverrides = false;
            this.bunifuLabel2.AutoEllipsis = false;
            this.bunifuLabel2.CursorType = null;
            this.bunifuLabel2.Font = new System.Drawing.Font("Segoe UI Semibold", 16F, System.Drawing.FontStyle.Bold);
            this.bunifuLabel2.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuLabel2.Location = new System.Drawing.Point(258, 548);
            this.bunifuLabel2.Name = "bunifuLabel2";
            this.bunifuLabel2.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel2.Size = new System.Drawing.Size(216, 30);
            this.bunifuLabel2.TabIndex = 2;
            this.bunifuLabel2.Text = "Made by: Jersey Baron";
            this.bunifuLabel2.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel2.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            this.bunifuLabel2.Click += new System.EventHandler(this.bunifuLabel2_Click);
            // 
            // bunifuLabel1
            // 
            this.bunifuLabel1.AllowParentOverrides = false;
            this.bunifuLabel1.AutoEllipsis = false;
            this.bunifuLabel1.Cursor = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.CursorType = System.Windows.Forms.Cursors.Default;
            this.bunifuLabel1.Font = new System.Drawing.Font("Segoe UI Semibold", 36F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.bunifuLabel1.ForeColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuLabel1.Location = new System.Drawing.Point(39, 82);
            this.bunifuLabel1.Name = "bunifuLabel1";
            this.bunifuLabel1.RightToLeft = System.Windows.Forms.RightToLeft.No;
            this.bunifuLabel1.Size = new System.Drawing.Size(379, 65);
            this.bunifuLabel1.TabIndex = 1;
            this.bunifuLabel1.Text = "OCR CONVERTER";
            this.bunifuLabel1.TextAlignment = System.Drawing.ContentAlignment.TopLeft;
            this.bunifuLabel1.TextFormat = Bunifu.UI.WinForms.BunifuLabel.TextFormattingOptions.Default;
            // 
            // Form1
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1006, 583);
            this.Controls.Add(this.Signup_tab);
            this.Controls.Add(this.bunifuGradientPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "Form1";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form1";
            this.Signup_tab.ResumeLayout(false);
            this.Signin_tab.ResumeLayout(false);
            this.Signin_tab.PerformLayout();
            this.tabPage2.ResumeLayout(false);
            this.tabPage2.PerformLayout();
            this.bunifuGradientPanel1.ResumeLayout(false);
            this.bunifuGradientPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuFormDock bunifuFormDock1;
        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel2;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton Sign_toggle;
        private Bunifu.UI.WinForms.BunifuPages Signup_tab;
        private System.Windows.Forms.TabPage Signin_tab;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton2;
        private Bunifu.UI.WinForms.BunifuTextBox txtpass;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel3;
        private System.Windows.Forms.TabPage tabPage2;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator1;
        private Bunifu.UI.WinForms.BunifuSeparator bunifuSeparator2;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton bunifuButton3;
        private Bunifu.UI.WinForms.BunifuLabel bunifuLabel4;
        private Bunifu.UI.WinForms.BunifuTextBox create_pass;
        private Bunifu.UI.WinForms.BunifuTextBox create_name;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton register_toggle;
        private Bunifu.UI.WinForms.BunifuTextBox create_email;
        public Bunifu.UI.WinForms.BunifuTextBox txtemail;
    }
}

